### ISSUE TITLE
Customized widgets → "Travel the world" and "Climb the mountains"

### ISSUE THREAD

**Issue by iifast1** [abhibagul/MagZ-Gaming-Free-Blogger-Template#1]
Hi,
Im having an issue with the customized widgets in _**MagZ-game-Red**_ , the carousel is now showing anything ... I know it's case sensitive when it comes to labels , I let it as default "travel" label, and made 9 posts like in the demo with labels : building , Mega Menu , mountain , travel
`<object class='magplus-widget' data-label='travel' data-type='list'></object>`

but it's not working , do i need more than 9 posts so I get it to work ?

Is this a payed version or mine has an issue ? 

https://i.imgur.com/PZBWtRl.png

btw, Grate content, keep it up 👍

**Comment by abhibagul** [comment]
can you share the URL of the blog so I can take a look at it.

**Comment by iifast1** [comment]
yes ! I tried this with blue the same issue with customized widget
https://freetutobluee.blogspot.com/

https://i.imgur.com/VbgGjcy.png
https://i.imgur.com/1ryYoy8.png

**Comment by abhibagul** [comment]
Updated the code. Please re-download the git and use the new template.
